//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantScore
    {
        public long APS_Id { get; set; }
        public Nullable<long> APS_APT_ApplicantId { get; set; }
        public Nullable<long> APS_RatingType { get; set; }
        public Nullable<decimal> APS_Score { get; set; }
        public Nullable<System.DateTime> APS_Date { get; set; }
        public string APS_IsActive { get; set; }
    }
}
