//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Tbl_Customer_Payment_Details = new HashSet<Tbl_Customer_Payment_Details>();
            this.Tbl_Customer_Payment_Details1 = new HashSet<Tbl_Customer_Payment_Details>();
            this.Tbl_Customer_Payment_Details2 = new HashSet<Tbl_Customer_Payment_Details>();
            this.Tbl_Customer_Vehicle_Details = new HashSet<Tbl_Customer_Vehicle_Details>();
            this.Tbl_Customer_Vehicle_Details1 = new HashSet<Tbl_Customer_Vehicle_Details>();
            this.Tbl_Customer_Vehicle_Details2 = new HashSet<Tbl_Customer_Vehicle_Details>();
            this.Tbl_Customer_Basic_Details = new HashSet<Tbl_Customer_Basic_Details>();
            this.Tbl_Log_Customer_Payment_Details = new HashSet<Tbl_Log_Customer_Payment_Details>();
            this.Tbl_Log_Customer_Payment_Details1 = new HashSet<Tbl_Log_Customer_Payment_Details>();
            this.Tbl_Log_Customer_Payment_Details2 = new HashSet<Tbl_Log_Customer_Payment_Details>();
            this.Tbl_Log_Customer_Vehicle_Details = new HashSet<Tbl_Log_Customer_Vehicle_Details>();
            this.Tbl_Log_Customer_Vehicle_Details1 = new HashSet<Tbl_Log_Customer_Vehicle_Details>();
            this.Tbl_Log_Customer_Vehicle_Details2 = new HashSet<Tbl_Log_Customer_Vehicle_Details>();
            this.Tbl_Log_Customer_Basic_Details = new HashSet<Tbl_Log_Customer_Basic_Details>();
            this.CompanyAccountDetails = new HashSet<CompanyAccountDetail>();
            this.CompanyAccountTransactions = new HashSet<CompanyAccountTransaction>();
            this.CompanyAccountTransactions1 = new HashSet<CompanyAccountTransaction>();
        }
    
        public long CMP_Id { get; set; }
        public string CMP_NameLegal { get; set; }
        public string CMP_NameDBA { get; set; }
        public Nullable<long> CMP_VDT_Id { get; set; }
        public long CMP_COT_Id { get; set; }
        public string CMP_CompanyDocument { get; set; }
        public string CMP_IsActive { get; set; }
        public Nullable<long> CMP_UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Payment_Details> Tbl_Customer_Payment_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Payment_Details> Tbl_Customer_Payment_Details1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Payment_Details> Tbl_Customer_Payment_Details2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Vehicle_Details> Tbl_Customer_Vehicle_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Vehicle_Details> Tbl_Customer_Vehicle_Details1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Vehicle_Details> Tbl_Customer_Vehicle_Details2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Basic_Details> Tbl_Customer_Basic_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Payment_Details> Tbl_Log_Customer_Payment_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Payment_Details> Tbl_Log_Customer_Payment_Details1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Payment_Details> Tbl_Log_Customer_Payment_Details2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Vehicle_Details> Tbl_Log_Customer_Vehicle_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Vehicle_Details> Tbl_Log_Customer_Vehicle_Details1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Vehicle_Details> Tbl_Log_Customer_Vehicle_Details2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Log_Customer_Basic_Details> Tbl_Log_Customer_Basic_Details { get; set; }
        public virtual VendorType VendorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAccountDetail> CompanyAccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAccountTransaction> CompanyAccountTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAccountTransaction> CompanyAccountTransactions1 { get; set; }
    }
}
