//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCodeLocationMapping
    {
        public long CLM_Id { get; set; }
        public long CLM_LocationId { get; set; }
        public long CLM_CCM_CostCode { get; set; }
        public long CLM_CCD_CostCode { get; set; }
        public string CLM_IsActive { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
