//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetailEmergency
    {
        public long POE_Id { get; set; }
        public long POE_LocationId { get; set; }
        public long POE_POT_Id { get; set; }
        public string POE_VendorName { get; set; }
        public Nullable<long> POE_QBKId { get; set; }
        public string POE_EmergencyComment { get; set; }
        public decimal POE_POAmount { get; set; }
        public Nullable<System.DateTime> POE_PODate { get; set; }
        public string POE_EmergencyPODocument { get; set; }
        public string POE_IsActive { get; set; }
    }
}
