//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetEmployeeLogin_Result1
    {
        public string EMP_EmployeeID { get; set; }
        public string EMP_IsActive { get; set; }
        public long DPT_Id { get; set; }
        public string DPT_Name { get; set; }
        public long VST_Id { get; set; }
        public string VST_Title { get; set; }
    }
}
